import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { useLanguage } from '../i18n/LanguageContext.jsx';
import { headTags, pageHead } from '../utils/pageHead.js';

/**
 * Keeps <head> matching the page on screen as the visitor navigates.
 *
 * The first page arrives with its head already written in by the build-time
 * pre-render; after that, routing is client-side and nothing else would update
 * the tab title, the description or the share tags. This swaps the whole
 * `[data-page-head]` set for the new page's, generated by the same
 * utils/pageHead.js the pre-render uses. The router's pathname excludes the
 * language prefix (it is the basename), which is exactly what pageHead wants.
 */
export default function useDocumentHead() {
  const { pathname } = useLocation();
  const { lang, t } = useLanguage();

  useEffect(() => {
    const head = pageHead(pathname, lang, t);
    document.head.querySelectorAll('[data-page-head]').forEach((el) => el.remove());
    document.head.insertAdjacentHTML('beforeend', headTags(head));
    // In dev, index.html's own <title> is still there (the pre-render
    // replaces it in production), and the browser shows the FIRST title.
    document.title = head.title;
  }, [pathname, lang, t]);
}
